const BOOKING_NEW = 0;
const BOOKING_PENDING = 1;
const BOOKING_SUCCESS = 2;
const BOOKING_FAIL = 3;

const PAYMENT_POINT = 1;
const PAYMENT_GATEWAY = 2;

const PAYMENT_PENDING = 1;
const PAYMENT_SUCCESS = 2;
const PAYMENT_FAIL = 3;

module.exports = {
	BOOKING_NEW,
	BOOKING_PENDING,
	BOOKING_SUCCESS,
	BOOKING_FAIL,
	PAYMENT_POINT,
	PAYMENT_GATEWAY,
	PAYMENT_PENDING,
	PAYMENT_SUCCESS,
	PAYMENT_FAIL,
};
