apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    name: api
spec:
  selector:
    matchLabels:
      name: api
  replicas: 3
  template:
    metadata:
      labels:
        app: api
        name: api
    spec:
      containers:
        - name: api
          image: registry.digitalocean.com/docker-registry-phuongnm/noval-api-gateway:$(echo $GITHUB_SHA | head -c7)
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 3000
          env:
            - name: LOGGER
              value: "true"
            - name: LOGLEVEL
              value: info
            - name: PORT
              value: "3000"
            - name: SERVICES
              value: src/services/api.service.js
            - name: TRANSPORTER
              value: nats://nats:4222
            - name: REDIS_URI
              value: redis://redis:6379
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    name: api-service
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - port: 80
      name: http
      targetPort: 3000
      protocol: TCP
    - port: 443
      name: https
      targetPort: 3000
      protocol: TCP
  selector:
    app: api

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - host: noval-api.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: api
              servicePort: 3000
